# -*- coding: utf-8 -*-
"""Sravanthi_Linear_regression_Assgn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LvI9GoAvl2mVy5EM9ywENJdS8YSlID5E
"""

import pandas as pd
import numpy as np

data = pd.read_csv("california_housing_train.csv")
data.head()

data.info()

data.shape

data.isnull().sum()

x = data.drop("median_house_value", axis=1)
y = data["median_house_value"]

#train-test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42

)

#model training
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
print("Model Trained Successfully")

#Prediction

predictions = model.predict(x_test)
print("predictions:",predictions[:10])

#Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

mae = mean_absolute_error(y_test,predictions)
mse = mean_squared_error(y_test,predictions)
r2 = r2_score(y_test,predictions)

print("MAE:",mae)
print("MSE:",mse)
print("R2 score:",r2)

import matplotlib.pyplot as plt
plt.scatter(y_test,predictions)
plt.xlabel("Actual values")
plt.ylabel("Predicted values")
plt.title("Actual vs Predicted values")
plt.show()

"""**What is regression?**
It measures relationship between a dependent variable and one or more independent variables.

**Difference between regression and classification?**
classification predicts discrete value or discrete output. Regression predict continuous values or continuous output.

**What is dependent variable?**
A dependent variable is the output variable that we want to predict using machine learning.

**What is overfitting?**
In machine learning overfitting occurs when a model fits too closely or even exactly to its training data, such that it can't make accurate predictions or conclusions from any data other than the training data.

**Explain regression line.**
A regression line is defined as a straight line that represents the relationship between a dependent variable(Y) and an independent variable (X) in a linear regression equation.


"""