# -*- coding: utf-8 -*-
"""Sravanthi_RNN_miniproject_Assgn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7db4pjwao1IIt-on7TKbZpHeEqQXXB2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

from tensorflow.keras.utils import to_categorical

text =  """Machine learning is a branch of artificial intelligence,
Machine learning helps computers learn patterns,
deep learning is a subset of Machine learning,
Artificial intelligence is transforming the world,
Data science uses machine learning techniques.
"""
#convert into lowercase

text = text.lower()
print(text)

#Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1
print("Total words:",total_words)
print(tokenizer.word_index)

#sequence generation
input_sequences = []
for line in text.split('\n'):
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequences.append(n_gram_sequence)

print(input_sequences[:5])

#padding (in order to make all the sequence same length)
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(
    pad_sequences(
        input_sequences,maxlen= max_sequence_len,padding='pre'
    )
)

print(input_sequences.shape)

x = input_sequences[:,:-1]
y = input_sequences[:,-1]
y = to_categorical(y,num_classes=total_words)

print(x.shape,y.shape)

#Dense layer
model = Sequential()
model.add(
    Embedding(
        input_dim= total_words,
        output_dim=64,
        input_length = max_sequence_len-1
    )
)

model.add(
    LSTM(128)
)

model.add(
    Dense(total_words,activation='softmax')
)

model.summary()

#compile model
model.compile(
    loss='categorical_crossentropy',
    optimizer ='adam',
    metrics=['accuracy']
)

#train model
history = model.fit(
    x,
    y,
    epochs=100,
    verbose=1
)

#Accuracy graph
plt.plot(history.history['accuracy'])
plt.title("Model Accuracy")
plt.xlabel('Epoch')
plt.ylabel("Accuracy")

plt.show()

#text generation function
def generate_text(seed_text,next_words):
  for _ in range(next_words):

    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences(
        [token_list],
        maxlen= max_sequence_len-1,
        padding='pre'
    )

  prediction = model.predict(token_list, verbose=0)
  predicted = np.argmax(prediction)

  output_word =""
  for word,index in tokenizer.word_index.items():
      if index == predicted:
        output_word = word
        break

  print("\nPredicted word:",output_word)
  seed_text += " " + output_word

  return seed_text

 #generate text
print(
    generate_text(
        "machine learning helps",
        5
    )
)

print(
    generate_text(
        "deep learning is a",
        5
    )
)

print(
    generate_text(
        "artificial intelligence is",
        5
    )
)

"""**What is RNN?**
Recurrent neural network is designed for sequential data where previous outputs influence future predictions.

**Why use RNN?**
As it remembers previous information and is suitable for text, speech, and time-series data

**Difference between CNN and RNN?**
CNN has no memory and captures spacial features which process data independently
where RNN has memory and captures temporal features and retain information from previous inputs.

**What is Vanishing Gradient Problem?**
During backpropagation, gradients become very small, making it difficult for the network to learn long-term dependencies.

**Difference between RNN and LSTM?**
The main difference between LSTM and RNN lies in their ability to handle and learn from sequential data. LSTMs are more sophisticated and capable of handling long-term dependencies, making them the preferred choice for many sequential data tasks.
"""