# -*- coding: utf-8 -*-
"""Sravanthi_Customer_segmentation_kmeans_Assgn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNWtQtJLUBy56LcvLglRFsGTOb5vgW9r
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

df = pd.read_csv("Mall_Customers.csv")
df.head()

df.shape

df.info()

df.isnull().sum()

duplicates = df.duplicated().sum()
print(duplicates)

df.describe()

#features for clustering
X = df[['Annual Income (k$)','Spending Score (1-100)']]
print(X.head())

#Normalize data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled[:5])

#Elbow method
wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters = i,
                  random_state = 42,
                  n_init = 10)
  kmeans.fit(X_scaled)
  wcss.append(kmeans.inertia_)

#plot elbow method
plt.figure(figsize =(8,5))
plt.plot(range(1,11),wcss,marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of clusters")
plt.ylabel('WCSS')
plt.show()

#train Kmeans
kmeans = KMeans(
    n_clusters=5,
    random_state = 42,
    n_init = 10
)
clusters = kmeans.fit_predict(X_scaled)
df['Cluster'] = clusters

#display cluster  labels
print(df[['CustomerID','Cluster']].head(10))

#no.of customers in each cluster
print(df['Cluster'].value_counts())

#visulaize clusters
plt.figure(figsize = (8,6))

plt.scatter(
    df['Annual Income (k$)'],
    df['Spending Score (1-100)'],
    c= df['Cluster']
)

plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Customer segmentation using k-means')
plt.show()

"""**What is Clustering? **
It is a unsupervised machine learning technique that groups similar data points into clusters based on their characteristics

**Difference Between Supervised and Unsupervised Learning?**
supervised learning excels in predictive tasks with known outcomes, while unsupervised learning is ideal for discovering relationships and trends in raw data.

**What is K-Means?**
K-Means is an unsupervised clustering algorithm that divides data into K clusters based on similarity.

**What is a Centroid?**
A centroid is the center point of a cluster.

**Explain Elbow Method.**
The elbow method is a visual heuristic used in machine learning to determine the optimal number of clusters(k) for algorithms like K-Means
"""