# -*- coding: utf-8 -*-
"""project_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdoHhmnGLQd2Eit2ks1DXI0rDXfhli1X
"""

import pandas as pd
import numpy as np

titanic = pd.read_csv("/1774007905444-titanic_dataset.csv")
titanic.head()

titanic.info()

#check null values
titanic.isnull().sum()

#remove null values
titanic = titanic.dropna()
titanic

#remove unwanted columns
titanic = titanic.drop(columns=['Cabin','Ticket','Name'],errors = 'ignore')

#remove unwanted rows
titanic = titanic.drop_duplicates()

# Average age of people who survived
Avg_Age = titanic[titanic['Survived']==1]['Age'].mean()
print("Average Age who survived:",Avg_Age)

#	average female who survived in each pclass
Female_Avg = titanic[(titanic["Sex"]=='female') & (titanic['Survived']==1)] \
                      .groupby("Pclass")["Age"].mean()
print("Female_avg:",Female_Avg)

#average male who survived in each pclass
Male_Avg =titanic[(titanic["Sex"]=='male') & (titanic['Survived']==1)] \
                      .groupby("Pclass")["Age"].mean()
print("Male_Avg:",Male_Avg)

# Cross validation
print("\nCross Validation - Gender vs Survival")
print(pd.crosstab(titanic["Sex"], titanic["Survived"]))

# group by male category
male_survivors = titanic[(titanic["Sex"]=='male') & (titanic['Survived']==1)]
groupby_male = male_survivors.groupby("Pclass")["Survived"].mean()
print(groupby_male)