# -*- coding: utf-8 -*-
"""Sravanthi_StopWord_Removal_Assgn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LC9ToLzMDcK35t90PfYV2iIfuvfd5ZsU
"""

import spacy
from collections import Counter
nlp = spacy.load("en_core_web_sm")
text = "Machine learning is a part of artificial intelligence, I am learning NLP and deep learning, I will learn PYTHON & ML!"
d = nlp(text)
print("ORIGINAL SENTENCE:", d)
#-----------Remove Stop word & punctuation + convert lower-------------
print("\n-----------Remove Stop word & punctuation + convert lower-------------")
tokens = [token.text.lower() for token in d if not token.is_stop if not token.is_punct ]
print(tokens)

#--------------Count words-----------------
print("\n--------------Count words-----------------")
print("TOTAL COUNT:",len(tokens))


#-----Cleaned Sentence---------
print("\n----------------Cleaned Sentence----------------")
cleaned_sentence = tokens
print("CLEANED SENTENCE:",cleaned_sentence)

"""**What are stopwords?**
Stop words are common words that do not add much meaning to text analysis.

**Why do we remove stopwords?**
We remove stop words to reduce unneccesary data and focus on important words.

**What is text preprocessing?**
Text preprocessing is the process of cla=eaning and preparing the text before NLP analysis includes converting into lower case, remove stop words and punctuations.

**Difference between stopword removal and stemming?**
Stop words removes unneccesary words and stemming reduces to roots form.

**What is punctuation removal?**
Removes punctuation marks like comma,question mark,!,.





"""