# -*- coding: utf-8 -*-
"""Sravanthi_Advance_tokenization_Assgn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glktS6DaKc7HSRAAkEYznObbX9Yg7MVi
"""

import spacy
from collections import Counter
#load model
nlp= spacy.load("en_core_web_sm")
text = "Hello! Contact us at support@gmail.com and visit https://openai.com"
d = nlp(text)
w = [tokens.text.lower() for tokens in d if not tokens.is_stop and not tokens.is_punct]
bow = Counter(w)
print(w)
print("\n bag of words:")
print(bow)

# ----------Word Tokenization-----------
print("\n----------Word Tokenization-----------")
for tokens in d:
  print(tokens.text)

# -----------Sentence Tokenization----------
print("\n-----------Sentence Tokenization----------")
for tokens in d.sents:
  print(f"Sentence: {tokens.text}")

# -----------Index position--------
print("\n-----------Index position----------")
for tokens in d:
  print(f"\n Token: {tokens.text} ------> Position: {tokens.idx}")

# -----------total number of tokens--------
print("\n-----------total number of tokens----------")
print("Total Count:",len(d))


#--------- punctuation tokens---------
print("\n--------- punctuation tokens-------")
for tokens in d:
  if tokens.is_punct:
    print(tokens.text)


#---------Stopword----------------
print("\n----------Stopword--------")
for tokens in d:
  print(f"\n{tokens.text}--->Stop Word :{tokens.is_stop}")

"""**What is tokenization?**
It is a process of converting sensitive data into randomized surrogate values called tokens.

**Difference between sentence and word tokenization?**
Sentence tokenization will convert complete sentence into individual sentence where word tokenization will breaks that sentence into individual word or punctuation.

**Why is tokenization important in NLP?**
Natural language processing will convert raw or messy data into meaningful tokens as the machine doesn't understand natural language directly.

**What are tokens?**
Tokens are basic building blocks of text and data used by artificial intelligence models to process and generate the models.

**What are punctuation tokens?**
Punctuation tokens will identify individual punctuations like comma,question mark, etc. that have been separated into distinct units during the text processing step called tokenization.

"""